# Templated by `cargo-generate` using https://github.com/danielhenrymantilla/proc-macro-template
name: Cron CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 8 * * 1,5'

jobs:
  # == TEST == #
  test-no-ui:
    name: (Check & Build &) Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        rust-toolchain:
          # Future-proof against compiler-regressions
          - beta
          - nightly
        cargo-locked: ['--locked']
        feature-nightly-dropck_eyepatch: ['', '--features nightly-dropck_eyepatch']
        include:
          # Also future-proof against semver breakage from dependencies.
          - rust-toolchain: stable
            cargo-locked: ''
    steps:
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          override: true
          toolchain: ${{ matrix.rust-toolchain }}

      - name: Clone repo
        uses: actions/checkout@v2

      - name: Update `Cargo.lock`
        if: matrix.cargo-locked != '--locked'
        run: cargo update -v

      - name: Cargo test
        uses: actions-rs/cargo@v1
        env:
          RUSTC_BOOTSTRAP: 1
        with:
          command: test
          args: |
            --features better-docs
            ${{ matrix.cargo-locked }}
            ${{ matrix.feature-nightly-dropck_eyepatch }}
